// diyerdo's proto
// Copyright (C) 2026 DrLarck
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
//
// ---
//
// Equipments service definition
syntax = "proto3";

option go_package = "github.com/diyerdo/proto/go/equipments/v1;equipments";

// EquipmentItemLookupService is the service for equipment item lookup
service EquipmentsService {
  // Returns the equipment item from the name and category
  rpc GetEquipmentFromNameAndCategory(GetEquipmentFromNameAndCategoryRequest) returns (GetEquipmentFromNameAndCategoryResponse);
}

// EquipmentItemCategory represents the category of the equipment item to look up
enum EquipmentCategory {
  EQUIPMENT_CATEGORY_UNSPECIFIED = 0;
  EQUIPMENT_CATEGORY_AMULET = 1;
  EQUIPMENT_CATEGORY_AXE = 2;
  EQUIPMENT_CATEGORY_BELT = 3;
  EQUIPMENT_CATEGORY_BOOTS = 4;
  EQUIPMENT_CATEGORY_BOW = 5;
  EQUIPMENT_CATEGORY_CLOAK = 6;
  EQUIPMENT_CATEGORY_DAGGER = 7;
  EQUIPMENT_CATEGORY_DOFUS = 8;
  EQUIPMENT_CATEGORY_DRAGOTURKEY = 9;
  EQUIPMENT_CATEGORY_HAMMER = 10;
  EQUIPMENT_CATEGORY_HAT = 11;
  EQUIPMENT_CATEGORY_LANCE = 12;
  EQUIPMENT_CATEGORY_MAGIC_WEAPON = 13;
  EQUIPMENT_CATEGORY_PET = 14;
  EQUIPMENT_CATEGORY_PETSMOUNT = 15;
  EQUIPMENT_CATEGORY_PICKAXE = 16;
  EQUIPMENT_CATEGORY_PRYSMARADITE = 17;
  EQUIPMENT_CATEGORY_RHINEETLE = 18;
  EQUIPMENT_CATEGORY_RING = 19;
  EQUIPMENT_CATEGORY_SCYTHE = 20;
  EQUIPMENT_CATEGORY_SEEMYOOL = 21;
  EQUIPMENT_CATEGORY_SHIELD = 22;
  EQUIPMENT_CATEGORY_SHOVEL = 23;
  EQUIPMENT_CATEGORY_STAFF = 24;
  EQUIPMENT_CATEGORY_SWORD = 25;
  EQUIPMENT_CATEGORY_TOOL = 26;
  EQUIPMENT_CATEGORY_TROPHY = 27;
  EQUIPMENT_CATEGORY_WAND = 28;
  EQUIPMENT_CATEGORY_WEAPON = 29;
}

// Equipment represents an equipment item
message Equipment {
  int32 id = 1;
  string name = 2;
  int32 level = 3;
  string icon_url = 4;
}

// GetEquipmentFromNameAndCategoryRequest represents the request to get the
// equipment items corresponding to given name and category
message GetEquipmentFromNameAndCategoryRequest {
  string name = 1;
  EquipmentCategory category = 2;
}

// GetEquipmentFromNameAndCategoryResponse represents the response to get the
// equipment items corresponding to given name and category
message GetEquipmentFromNameAndCategoryResponse {
  repeated Equipment equipment_items = 1;
}
