// diyerdo's proto
// Copyright (C) 2026 DrLarck
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
//
// ---
//
// Equipments service definition
syntax = "proto3";

option go_package = "github.com/diyerdo/proto/go/equipments/v1;equipments";

// EquipmentItemLookupService is the service for equipment item lookup
service EquipmentsService {
  // Returns the equipment item from the name and category
  rpc GetEquipmentFromNameAndCategory(GetEquipmentFromNameAndCategoryRequest) returns (GetEquipmentFromNameAndCategoryResponse);
}

// EquipmentItemCategory represents the category of the equipment item to look up
enum EquipmentCategory {
  EQUIPMENT_CATEGORY_UNSPECIFIED = 0;
  EQUIPMENT_CATEGORY_BOOTS = 1;
}

message Equipment {
  int32 id = 1;
  string name = 2;
  int32 level = 3;
  string icon_url = 4;
}

message GetEquipmentFromNameAndCategoryRequest {
  string name = 1;
  EquipmentCategory category = 2;
}

message GetEquipmentFromNameAndCategoryResponse {
  optional Equipment equipment_item = 1;
}
